src/ctMock.ts, src/repositories/cart.ts, src/repositories/product.ts, src/services/cart.test.ts, src/services/my-cart.test.ts, src/services/my-cart.ts, src/services/product.test.ts, src/types.ts
This PR implements `/me/carts` endpoint
And the following cart update actions:
- addLineItem
- removeLineItem
- setBillingAddress
- setCountry
- setCustomerEmail
- setCustomField
- setCustomType
- setLocale
- setShippingAddress
=> Implement MyCart service

src/repositories/category.ts
Add missing `externalId` attribute.
=> category: Add external_id attribute

src/repositories/customer.ts
adds action for changing customer email testing
=> feat: add customer changeEmail action

src/repositories/customer.ts, src/services/my-customer.ts, yarn.lock
I add the sign in function and route.
=> Add sign in.

src/repositories/cart.ts, src/services/cart.test.ts
- Improve price selection; Not 100% perfect yet but better then just grabbing the first element from `prices`
- Add more attributes which are taken from the CartDraft when creating a cart
=> cart improve price selection and attributes

src/repositories/product-type.ts
Related: https://github.com/labd/terraform-provider-commercetools/pull/276
=> Implement product type attribute definition actions

package.json, src/projectAPI.ts, src/repositories/helpers.ts, src/repositories/product-discount.ts, src/repositories/product-projection.ts, src/repositories/store.ts, src/repositories/type.ts, src/services/custom-object.test.ts, src/storage.ts, src/types.ts, yarn.lock
Commercetools added the resources `standalone-price` and `product-price` which were missing
=> Fix typing issues introduced with new resources in commercetools

src/repositories/product-projection.ts
Add support for product-projection search expand.
=> feat: Added expand support for product-projection search

Dockerfile, src/repositories/product.ts, src/services/product.test.ts
Add `addExternalImage` and `removeImage` product update actions
=> feat: Add addExternalImage and removeImage product update actions

CHANGELOG.md, package.json
=> release 0.11.0

src/repositories/product.ts, src/services/product.test.ts
Add `moveImageToPosition` product update action
=> feat: add moveImageToPosition product update action

src/services/index.ts, src/services/standalone-price.test.ts, src/services/standalone-price.ts
The solution addresses the issue https://github.com/labd/commercetools-node-mock/issues/61
=> Adding support for standalone-price 

.changeset/fresh-ligers-speak.md, src/repositories/product.ts, src/services/product.test.ts
- Add `addPrice` product update action
- Add `changePrice` product update action
- Add `removePrice` product update action
=> feat: add addPrice, changePrice and removePrice product update actions

Dockerfile, package.json
=> chore: upgrade pnpm to working mac version

.changeset/fuzzy-mugs-wink.md, src/helpers.ts, src/product-projection-search.ts, src/repositories/product-projection.ts, src/services/abstract.ts, src/services/product-projection.ts
- Improve mock implementation of product projection search
- Don’t error or on facet `counting products`
=> Product projection search improvements

src/repositories/cart-discount.ts, src/services/cart-discount.test.ts
- Added [SetCustomType action](https://docs.commercetools.com/api/projects/cartDiscounts#set-custom-type) for CartDiscount
- Added test for SetCustomType on Cart Discounts
__Note:__ required for pull request [#420](https://github.com/labd/terraform-provider-commercetools/pull/420)
=> Feature/SetCustomType action for CartDiscount

src/repositories/business-unit.ts, src/repositories/helpers.ts, src/services/business-units.test.ts, src/services/business-units.ts, src/services/index.ts
- Implements business unit repository
- Adds business unit service
- Adds utility helpers useful for business unit creation
=> feat(business-units): add repository and service

.changeset/calm-tigers-invent.md, src/ctMock.ts, src/exceptions.ts, src/lib/password.ts, src/oauth/server.ts, src/oauth/store.ts, src/repositories/customer.ts, src/services/my-customer.ts
- Improve customer authentication
- Validate the uniqueness of a customer email
=> Implement customer authentication

src/repositories/category.ts, src/services/category.test.ts
=> feature: add category actions

.changeset/cuddly-toes-travel.md, src/repositories/order.ts, src/services/order.test.ts
https://docs.commercetools.com/api/projects/orders#update-syncinfo
=> feat(order): add support for syncInfo

.changeset/hot-jokes-cheer.md, src/repositories/order/actions.ts, src/services/order.test.ts
https://docs.commercetools.com/api/projects/orders#set-customer-id
=> feat(order): add setCustomerId action

.changeset/twelve-jokes-dream.md, src/repositories/cart/actions.ts
Also remove todo comments that were already resolved
=> chore: add changeset for #223

.changeset/metal-onions-itch.md, src/ctMock.ts
- allow for large document sizes for testing purposes
=> feat: allow large documents

package.json, src/repositories/cart/index.test.ts
- Use `biome check --fix` instead of `biome format --fix`
=> fix: set biome to use `biome check --fix` instead of `biome format --fix`

.changeset/major-cases-make.md, src/repositories/cart/index.test.ts, src/repositories/cart/index.ts
- Added support for business units on cart creation
=> feat: added support for business units on cart creation
