src/services/product-projection.test.ts
src/storage.ts

When requesting a resource which doesn't exists via withKey, and the expand query string, an error was raised.
For example:
`/us-unittest/product-projections/key=invalid?expand=categories%5B*%5D`
This PR implements a fix for this, that expand is only executed when resource is found.

fix getByKey with expand when resource not found

---

src/repositories/product-projection.ts
src/services/product-projection.test.ts

- product-projection search without filters throws error: **Cannot read property 'replace' of undefined**
- Implemented support for filter.query in product-projection search

fix productProjection search without filters

---

src/repositories/abstract.ts
src/repositories/product-projection.ts
src/services/abstract.ts
src/services/product-projection.test.ts

This PR adds support for offset and limit query strings.
For example, if you request `/product-projects/?offset=10&limit=10`, the response will also return `{offset: 10, limit: 10}`.

Add support for offset and limit query string

---

src/repositories/product-discount.ts

This seems to be how CT works.
Related https://github.com/labd/terraform-provider-commercetools/pull/266

product_discount: Set undefined if the provided localized string object is empty

---

package.json
tsup.config.js

The exports syntax is used to define which files are used for commonjs
and which ones for esmodules.
I have also removed the commonConfig and added it defineConfig since it's used once

feat(package): use exports syntax for cjs and mjs output

---

CHANGELOG.md
src/repositories/customer.ts
src/services/customer.test.ts

This PR adds the `setAuthenticationMode` update action to the Customer resource. It is used for switching a customer to use External Authentication.
The change is test-covered for the cases I could imagine and which I tested against a real Commercetools project.
This PR also adds a test for the existing `changeEmail` update action.

Add setAuthenticationMode update action to customer

---

.babelrc
.changeset/early-cameras-warn.md
.eslintrc.js
.github/workflows/release.yml
Dockerfile
package.json
pnpm-lock.yaml

- Dropped support for `node` version 14
- Updated `node` to version 18
- Updated `pnpm` to version 8
- Shared eslint config
- Updated major semver version by using `changeset`

BREAKING: upgrade node, pnpm, eslint shared package, dropped support for node 14

---

.changeset/red-keys-melt.md
src/lib/predicateParser.ts
src/repositories/product-projection.ts
src/services/abstract.ts
src/services/product-projection.test.ts
src/services/product-projection.ts

This didn’t work at all previously. This implementation should make the
staged/non-staged work correctly and should include proper filtering.
Specific storeProjection or localeProjections are not supported yet

Fix the product projection query endpoint

---

.changeset/sixty-turtles-happen.md
src/repositories/cart.ts
src/services/cart.test.ts

The cart recalculate action is missing in this package, and will raise an error now because of this. I just implemented a dummy action to fix its not raising an error anymore. And I think it's fine, because commercetools does some things under the hood when calling this action. (see my code comment about this)

feat: add cart recalculate action

---

.changeset/wet-papayas-approve.md
src/repositories/cart.ts
src/services/cart.test.ts

It doesn't apply discounts to the cart, but just set the field values.
https://docs.commercetools.com/api/projects/carts#set-directdiscounts

feat(cart): add setDirectDiscounts action

---

.changeset/nasty-knives-camp.md
src/lib/predicateParser.test.ts
src/lib/predicateParser.ts

Small fix to generating of a matching function in the predicate parser. When trying to match an object in an array with multiple conditions it would try to match the conditions individually for all objects in the array. While it should try to match all the conditions for at least 1 item in the array.
Example:
Query: `array(stringProperty="foo" and numberProperty=2345)` would have matched if the array contained an object with `stringProperty="foo"` and one object with: `numberProperty=2345`. Instead of matching only if the array contained an object with both `stringProperty="foo" and numberProperty=2345`.

fix: predicate parser correctly match objects in array

---

.changeset/dirty-rockets-crash.md
package.json
pnpm-lock.yaml

I'm using this library in a project and Wiz scan is showing that Express 4.18.2 has vulnerability that was fixed in the version 4.19.2
https://github.com/advisories/GHSA-rv95-896h-c2vc
Issue #180

feat: update express version to 4.19.2

---

.changeset/lucky-chairs-arrive.md
src/repositories/custom-object.ts
src/services/custom-object.test.ts

The arguments for the `postProcessResource` has been changed in the following commit:
https://github.com/labd/commercetools-node-mock/commit/08e651b5d60554b5bd40862b134ece0b11833a91#diff-b5c53b0ebb282ab7281fc320a01f5eabd1699676f6606c175ac72a42260f6bed
Therefore we also need to update this postProcessResource-call for custom objects.

fix: custom-objects with container results

---

.changeset/twelve-schools-join.md
src/repositories/order/actions.ts
src/services/order.test.ts

This changes add `changePaymentState` in the order action to handle setting of shipmentState property, which is missing for the test for our project.

Add change shipment state action in order action

---

.changeset/wet-poems-appear.md
src/repositories/cart/actions.ts
src/repositories/shopping-list/actions.ts

Sets default of addedAt in cart,
Allows override to be passed in cart
Allows override to be passed in wishlist
This is important as we order line items on the addedAt value, when we exchange a line item, we pass the addedAt value to preserve the order and need to test this

fix: allow addedAt override in add to wishlist and add to cart 

---

.changeset/stupid-turtles-boil.md
src/repositories/customer/actions.ts
src/services/customer.test.ts

Add support for the following customer update actions:
- addAddress
- addBillingAddressId
- addShippingAddressId

feat: add support for customer address actions

---

.changeset/green-brooms-cover.md
src/repositories/order/actions.ts
src/services/order.test.ts

Add support for `setPurchaseOrderNumber` order update action.

feat(order): add support for setPurchaseOrderNumber order update action

---

.changeset/afraid-donuts-change.md
src/repositories/cart/actions.ts
src/services/cart.test.ts

Added the setShippingAddressCustomType and setBillingAddressCustomType actions to the cart repository

Feat: address custom type actions

---

.changeset/shy-lobsters-hammer.md
package.json
pnpm-lock.yaml
src/ctMock.ts
src/index.test.ts

Removes the dependency `light-my-request` which was added in v2.2.0 to circumvent an internal issue of msw (https://github.com/mswjs/interceptors/issues/443). This has since been fixed and this should therefore no longer be necessary.

fix(core): Remove `light-my-request` dependency

---

.changeset/real-onions-sparkle.md
package.json
pnpm-lock.yaml
src/ctMock.ts
src/index.test.ts

This reverts commit 7473d9e3a597e08bfce39cfba7dbceb77dfaa1b8.

Revert "fix(core): remove `light-my-request` dependency"

---

.changeset/weak-scissors-jam.md
src/repositories/customer/index.ts
src/services/customer.test.ts
src/services/my-customer.test.ts

Add ability to set shipping and billing addresses when creating customer
via the `shippingAddresses` and `billingAddresses`

feat: set addresses on customer create

---

.changeset/gorgeous-turtles-judge.md
package.json
pnpm-lock.yaml
src/repositories/abstract.ts
src/repositories/customer/actions.ts
src/services/customer.test.ts

This includes adding support for:
- `removeAddress`,
- `removeBillingAddressId`
- `removeShippingAddressId`
- `setCustomerGroup`
- `setDateOfBirth`
- `setDefaultShippingAddress`
- `setDefaultBillingAddress`
- `setMiddleName`
- `setTitle`
This change also improves the testing of some actions and introduces
`fishery` as dependency to ease the test creation

Improve mocking of customer updates.

---

.changeset/curly-carpets-learn.md
src/repositories/customer/index.test.ts
src/repositories/customer/index.ts

Passing store references when creating a customer currently doesn't associate the customer to the store. This adds that functionality
**Changes:**
- Set store references on the customer resource
- Map any storeId references to storeKey references (since only storeKey reference are saved on the customer)

fix(customer): add setting of stores on customer

---

.changeset/ten-rocks-walk.md
src/repositories/customer/index.test.ts
src/repositories/customer/index.ts
src/services/my-customer.test.ts

Add support for querying a customer with lowercaseEmail.

feat(customer): add lowercaseEmail support

---

.changeset/cold-bugs-approve.md
src/repositories/customer/index.test.ts
src/repositories/customer/index.ts

Empty arrays for the stores of a customer were wrongfully check for empty arrays. Fixes issue introduced in #249.

fix(customer): customer repository allow no stores

---

.changeset/lovely-rabbits-hear.md
src/repositories/business-unit.ts

Adding associates fails, if associates value is not set to empty array when creating the business unit.

fix: set empty array for associates when creating a business unit

---

.changeset/pink-hornets-compete.md
src/repositories/associate-role.ts
src/repositories/business-unit.ts
src/repositories/product-selection.ts

- Added missing mutations for custom fields on associate roles, product selections and business units

feat(custom-fields): Added custom field mutations

---

.changeset/silent-scissors-remain.md
src/ctMock.ts
src/projectAPI.ts

The `ctMock.add()` function directly inserts objects in the in-memory store of commercetools mock, which could result in invalid objects being processed due to missing validation, or pre processing hooks.
This change introduces a new method `unsafeAdd()` to still have this option available while clearly signalling you shouldn't normally use it. 
Note that this for now only shows a deprecation warning, the functionality will still be there for the foreseeable future

Deprecate ctMock.add()

---

.changeset/young-bats-boil.md
src/ctMock.ts

This allows us to use the handlers for one-time setup:
e.g.
```
const mswServer = setupServer(...ctMock.getHandlers());
```

feat: Add `ctMock().getHandlers()`

---

.changeset/neat-cougars-bake.md
src/repositories/cart/actions.ts
src/repositories/shopping-list/actions.ts
src/services/cart.test.ts
src/services/shopping-list.test.ts

Add support to key field in the addLineItem actions. 
CT docs: https://docs.commercetools.com/api/projects/carts#add-lineitem

feat: add key support to addLineItem

---

.changeset/tall-bags-invite.md
src/product-search.ts
src/services/product.test.ts

The current product search mock doesn't take querying on stock availability into account. Commercetools allows searching on the product variants availability attributes: `availableQuantity`, `isOnStock` & `isOnStockForChannel`. These attributes are not by default available on each product, and needed to be added to the resources that are used for the product search.
- Add availability object to each resource that is used for the product search
- Move product search tests to each own test suite, so it won't be affected by other tests.

feat: add support for searching on availability in productsearch

---

.changeset/slow-parts-shine.md
src/repositories/cart/index.test.ts
src/repositories/cart/index.ts

In the current state this mock service is able to handle custom line item fields if they are being sent of a cart update action. However, the service is not able to handle these custom fields upon cart creation.
This PR aims to fix that by adding the custom field handler.
The test additions are a bit crude, I'll happily change/remove them per your suggestions.

Add processing of line item custom types on cart creation

---

.changeset/fresh-deer-invent.md
src/services/my-business-unit.test.ts
src/services/my-business-unit.ts

Add support for get/delete/post endpoints of my-business-units.

feat(me/business-units): add missing routes

---

.changeset/rich-pens-joke.md
package.json
pnpm-lock.yaml

This means getHandlers() will return `RequestHandler[]` instead of `HttpHandler[]`.

chore: update msw dependency to 2.8.4
